export const allRoutes = {
  home: "/",
  auth: "/auth",
  forgetPassword: "/auth/forgot-password",
  resetPassword: "/auth/reset-password",
  dashboard: "/dashboard",
  cinema: "/cinema-setup",
  movies: "/movies",
  create: "create",
  edit: "edit",
  details: "details",
  concessions: "/concessions",
  tickets: "/tickets",
  staffs: "/staffs",
  customers: "/customers",
  scheduling: "/scheduling",
  signage: "/signage",
  reports: "/reporting",
  settings: "/settings",
  audit: "/audit",
  paymentSuccess: "/payment-success",
};
