export const allRoutes = {
  home: "/",
  auth: "/auth",
  dashboard: "/dashboard",
  prospects: "/prospects",
  customers: "/customers",
  policies: "/policies",
  claims: "/claims",
  staffs: "/staffs",
  agents: "/agents",
  business: "/business",
  products: "/products",
  underwriters: "/underwriters",
  reports: "/reports",
  roles: "/roles",
  profile: "/profile",
  create: "create",
  edit: "edit",
  details: "details",
  auditTrail: "/audit-trail",
  accounting: "/accounting",
};
