const urls = {
  login: "/auth/login",
  cinema: "/cinema",
  movie_clas: "/movie-classification",
  screen_types: "/screen-type",
  seat: "/seat",
  showtime_status: "/showtime-status",
  screen: "/screen",
  movie: "/movie",
  showtime: "/showtime",
  role: "/role",
  product_cat: "/product-category",
  product: "/product",
  product_available: "/product/available",
  inventory: "/inventory",
  price_rule: "/price-rule",
  audit: "/audit-trail",
  user: "/user",
  staff: "/user",
  permission: "/permission",
  vat_config: "/vat-config",
  role_permission: "/role-permission",
  purchase_initiate: "/purchase/initiate",
};

export default urls;
